### ISSUE TITLE
Make Poison an optional module

### ISSUE THREAD

**Issue by devinus** [PragTob/benchee_json#2]
This will allow me to use benchee_html in Poison itself. :)

**Comment by PragTob** [comment]
Argh... I've never seen this issue, must have hit read some time.. doohh. Sorry.

@devinus any tips how to go about that? Just remove it from dependencies and when started be like "Woops we'd really need Poison" or what can we do/what is the problem? 

(Couldn't you override it to `.` in the mean time? :))

**Comment by devonestes** [comment]
@PragTob We can fix this - I'll have a PR in a second.

**Comment by devonestes** [comment]
So, I asked the community for their input, and despite the thread getting hijacked pretty quickly, their answer was basically, "sorry, this isn't an easily solvable problem." https://elixirforum.com/t/working-around-circular-library-dependency/9239

The reason I hesitate to make Poison an optional dependency is because if any user wanted to use the `benchee_html` formatter, they'd then have to add `benchee_html` and `poison` to their `mix.exs` deps, and that seems like it's a pretty sub-optimal user experience - especially since `poison` really is a true dependency in every other project except for `poison`.

**Comment by PragTob** [comment]
yes, apparently through specifying the dependency with a path (and potentially an override) I think it should be possible to use for `poison` itself like this.

As it'd be harder for others I think I'm closing out here unless someone else has a good idea how to solve this.

@devonestes thanks for all the work poured in!
